[directories]
data = 'data/'

[data]
transactions_directory = 'tables/transactions_20210228_20210827_snapshot/'
merchants_file_loc = 'tables/tbl_merchants.parquet'
transactions_output = 'curated/transactions.parquet'